# Generated by Django 4.1.6 on 2023-02-14 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='endpoints.categoria'),
        ),
    ]
